# Generated by Django 5.2.6 on 2025-09-18 23:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_priority_name_alter_status_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
